def skipRemainingStages = false

pipeline {
   agent any
	tools {
		maven 'mvn3'
	}
      stages{
			stage('Build'){
				steps{
					sh script: 'mvn  -f CubeGenerator/pom.xml clean package'
					
				}
			}
			stage('Upload to NEXUS'){
				steps{
					nexusArtifactUploader artifacts: [[
						artifactId: 'CubeGenerator', 
						classifier: '', 
						file: 'CubeGenerator/target/CubeGenerator-1.0-SNAPSHOT.jar', 
						type: 'jar']], 
						credentialsId: '91e0f520-012d-4fea-ba3a-5cf234aeb32d', 
						groupId: 'com.javatpoint', 
						nexusUrl: 'localhost:8081', 
						nexusVersion: 'nexus3', 
						protocol: 'http', 
						repository: 'simpleapp-release', 
						version: '1.0-4'
					
				}
			}
			stage("Stage 1") {
            steps {
					script {
					    skipRemainingStages = true

					    println "skipRemainingStages = ${skipRemainingStages}"
					}
		    	}
			}

			stage("Stage 2") {
			    when {
					expression {
					    !skipRemainingStages
					}
			    }

			    steps {
					script {
					    println "This text wont show up...."
					}
			    }
			}

			stage("Stage 3") {
			    when {
					expression {
					    !skipRemainingStages
					}
			    }

			    steps {
					script {
					    println "This text wont show up...."
					}
			    }
			}
		}
} 
