def skipRemainingStages = false

pipeline {
   agent any
	tools {
		maven 'mvn3'
	}
      stages{
			stage("Stage 1") {
            steps {
					script {
					    skipRemainingStages = true

					    println "skipRemainingStages = ${skipRemainingStages}"
					}
		    	}
			}
			stage("Stage 2") {
			    when {
					expression {
					    !skipRemainingStages
					}
			    }

			    steps {
					script {
					    println "This text wont show up...."
					}
			    }
			}

			stage ('1 choice') {
		      when {
		                expression { choice == '1'}
		            }
		            steps {
		                echo "Hello, Choice 1!"
		            }
		    }
		    stage ('2 choice') {
		      when {
		                expression { choice == '2'}
		            }
		            steps {
		                echo "Hello, Choice 2!"
		            }
		    }
		   stage ('3 choice') {
		      when {
		                expression { choice == '3'}
		            }
		            steps {
		                echo "Hello, Choice 3!"
		            }
		        }

			
		}
} 
